import type { Metadata } from 'next';
import './globals.css';
import 'modern-normalize/modern-normalize.css';
import { Header } from '@/shared/ui/components/header';
import { Footer } from '@/shared/ui/components/footer/footer';

export const metadata: Metadata = {
  title: '11host',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
